var r = ["Wasay", "Ahad", "Huzaifa", "Waleed", "Bilal"];
console.log("Mr.", r[0], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[1], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[2], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[3], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[4], "are invited for a dinner in my house tonight!");
console.log("Unfortunately!,", r[2], "can't make to the dinner");
r[2] = "Saqib";
console.log("Now Mr. ", r[2], "will join us tonight");
console.log("Mr.", r[0], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[1], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[2], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[3], "are invited for a dinner in my house tonight!");
console.log("Mr.", r[4], "are invited for a dinner in my house tonight!");
